### ISSUE TITLE
Players getting stuck in doors, elevators, etc.

### ISSUE THREAD

**Issue by Cads182** [wootguy/AntiRush#1]
I'm wondering if it's possible to do something to prevent this?, somehow detects a door when a player has finished the map, and it's nonsolid, making the door works normal or prevent players getting stuck

**Comment by wootguy** [comment]
The non-solid thing probably isn't needed anymore now that there's an [antiblock](https://github.com/wootguy/AntiBlock) plugin. I would just disable the nonsolid cvar if it's causing problems.
